# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef80ffe0cbd7648f87ef5ab26d70310409ba531b62ceb7139a42a0ad7f5158e81eed4083a3cc3c6dd222a9cd48157ca85cdf2c70f7a929a2c3ee6003306224cb

test:
  secret_key_base: eb71eaacd329c0f6a766a42968847a25b9ebe8f882b7eba2a5d70436e5fe316f714c8e224cf3026852948aa60c7ea3879efa4c79550834190b24225e85e68b3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
